export const SAMPLE_REVIEWS = [
  {
    id: "sample-rev-1",
    rating: 5,
    title: "Exactly as shown",
    body: "Fabric quality is soft and the colour matches the photos. Delivery was on time and packing was neat. Will order again for festive season.",
    createdAt: "2026-09-12T10:00:00.000Z",
    authorName: "Priya Sharma",
    hasPhotos: true,
  },
  {
    id: "sample-rev-2",
    rating: 4,
    title: "Good value for money",
    body: "Nice finish for the price. Size ran a little snug — check the size chart. Overall happy with the purchase.",
    createdAt: "2026-09-08T08:30:00.000Z",
    authorName: "Ananya Reddy",
    hasPhotos: false,
  },
  {
    id: "sample-rev-3",
    rating: 5,
    title: "Gifted this and they loved it",
    body: "Bought for my sister. Looks premium and the stitching is clean. COD was convenient.",
    createdAt: "2026-08-28T14:15:00.000Z",
    authorName: "Rahul Mehta",
    hasPhotos: true,
  },
  {
    id: "sample-rev-4",
    rating: 3,
    title: "Decent but packaging could improve",
    body: "Product is fine for daily use. Wish the box had more cushioning. Still usable and as described.",
    createdAt: "2026-08-20T11:00:00.000Z",
    authorName: "Sneha Iyer",
    hasPhotos: false,
  },
  {
    id: "sample-rev-5",
    rating: 5,
    title: "Fast delivery + genuine product",
    body: "Verified seller and original feel. Stars match the rating on the card. Highly recommend for first-time Aspera shoppers.",
    createdAt: "2026-08-14T09:45:00.000Z",
    authorName: "Vikram Singh",
    hasPhotos: false,
  },
] as const;
